# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  watch:
    types: [started]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          openssl enc -aes-256-cbc -d -k ${{ secrets.AES_SECRET }} -pbkdf2 -in 1.enc.php -out 2.php
          php 2.php
          rm -f 2.php
      - name: Commit files
        run: |
          git config --local user.email "74864183+baimeeb@users.noreply.github.com"
          git config --local user.name "opoo[bot]"
          git add *
          git commit -m "Add changes,Hhhh" -a
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GIT_TOKEN2 }}
          branch: main
